# Source: https://miladezzat.medium.com/deploy-to-google-cloud-run-3cffcb2dbd5f

name: Backend CD

on:
  workflow_dispatch:

  # This will run when merging backend PRs into main
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "Dockerfile"
      - ".github/workflows/backend_cd.yml"

  # This will only run on PRs for testing the workflow itself    
  pull_request:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - ".github/workflows/backend_cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-west1
      AR_REPOSITORY: backend-repo
      SERVICE_NAME: backend
      IMAGE_NAME: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth-to-google-cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          flags: |
            --add-cloudsql-instances=${{ secrets.DB_CONNECTION_NAME }}
            --set-secrets="DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,DB_CONNECTION_NAME=DB_CONNECTION_NAME:latest"
            --set-env-vars="DB_PORT=5432,USE_CLOUD_SQL=true,DB_HOST=/cloudsql/${{ secrets.DB_CONNECTION_NAME }}"
        
      # This creates an alias URL which can be used to check if the deployment was successful
      # The stable backend URL is still https://backend-163526067001.us-west1.run.app/
      - name: Show deployed URL
        run: |
          echo "Successfully deployed new revision!"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format='value(status.url)'
